In [7]:
# loan Approval expert system

In [8]:
def approve_loan(income, credit_score, existing_loan):
    if income >= 50000 and credit_score >= 700 and not existing_loan:
        return "loan Approved"
    elif income >= 30000 and credit_score >= 650:
        return "Further Review Required"
    else:
        return "Loan Rejected"

In [9]:
income = 70000
credit_score = 750
existing_loan = False

In [10]:
# Inference Engine

In [11]:
decision =  approve_loan(income, credit_score, existing_loan)

In [12]:
decision

'loan Approved'

In [13]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [14]:
# Create sample data

In [15]:
data = {
    "Hours_studies":[1,2,3,4,5,6,7,8,9,10],
    "Marks":[35,40,50,55,60,65,70,78,85,90]
}

In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame(data)

In [18]:
print(df)

   Hours_studies  Marks
0              1     35
1              2     40
2              3     50
3              4     55
4              5     60
5              6     65
6              7     70
7              8     78
8              9     85
9             10     90

In [19]:
# Separate input (x) and output (y)

In [20]:
x = df[["Hours_studies"]]
y = df["Marks"]

In [21]:
print(x)

   Hours_studies
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10

In [22]:
print(y)

0    35
1    40
2    50
3    55
4    60
5    65
6    70
7    78
8    85
9    90
Name: Marks, dtype: int64

In [23]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\hp\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [24]:
import sklearn
print(sklearn.__version__)

1.7.2

In [25]:
# Spilt data into training and testing

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [28]:
print(X_train)

   Hours_studies
5              6
0              1
7              8
2              3
9             10
4              5
3              4
6              7

In [29]:
print( X_test)

   Hours_studies
8              9
1              2

In [30]:
print( y_train)

5    65
0    35
7    78
2    50
9    90
4    60
3    55
6    70
Name: Marks, dtype: int64

In [31]:
print(y_test)

8    85
1    40
Name: Marks, dtype: int64

In [32]:
# Import LinearRegression

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
# Create the train model

In [35]:
model = LinearRegression()

In [36]:
model.fit(X_train,y_train)

LinearRegression()

In [37]:
# Make PredictionS

In [38]:
y_pred = model.predict(X_test)

In [39]:
y_pred

array([83.54310345, 42.20689655])

In [40]:
y_test

8    85
1    40
Name: Marks, dtype: int64

In [41]:
X_test

   Hours_studies
8              9
1              2

In [42]:
from sklearn.metrics import mean_squared_error

In [43]:
mean_squared_error(y_test,y_pred)

3.496469976218767

In [44]:
#Predict for new value

In [45]:
new_hours = pd.DataFrame({"Hours_studies":[7.5]})

In [46]:
new_hours

   Hours_studies
0            7.5

In [47]:
predicted_marks = model.predict(new_hours)

In [48]:
predicted_marks

array([74.68534483])

In [49]:
import matplotlib.pyplot as plt

In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [51]:
%pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\hp\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [52]:
plt.scatter(X,y,label="Actual Data")
plt.plot(X,model.predict(X),color="red",label="Regression Line")
plt.xlabel("Hours Studied")
plt.ylabel("Marks Obtained")
plt.title("Linear Regression")
plt.legend()
plt.show()

NameError: name 'X' is not defined

In [53]:
# y = mx + c

In [54]:
# x = input value
# y = Predicted value
# m = slope
# c = intercept

In [55]:
from sklearn.datasets import fetch_california_housing

In [56]:
housing = fetch_california_housing()

In [57]:
housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [58]:
housing.target_names

['MedHouseVal']