In [1]:
# student3.csv

In [5]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv('student.csv')
df;

In [11]:
df.shape

(10, 5)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   class   10 non-null     object
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

In [13]:
# fix structural errors

In [14]:
df['name'];

In [15]:
df['name'] = df['name'].str.title()

In [16]:
df

   roll     name class  marks  age
0     1     Anil    TE  56.77   22
1     2     Amit    TE  59.77   21
2     3   Aniket    BE  76.88   19
3     4  Ajinkya    TE  69.66   20
4     5     Asha    TE  63.28   20
5     6   Ayesha    BE  49.55   20
6     7     Amar    BE  65.34   19
7     8    Amita    BE  68.33   23
8     9     Amol    TE  56.75   20
9    10    Anmol    BE  78.66   21

In [17]:
df['class']

0    TE
1    TE
2    BE
3    TE
4    TE
5    BE
6    BE
7    BE
8    TE
9    BE
Name: class, dtype: object

In [18]:
df['marks']

0    56.77
1    59.77
2    76.88
3    69.66
4    63.28
5    49.55
6    65.34
7    68.33
8    56.75
9    78.66
Name: marks, dtype: float64

In [19]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [20]:
df.columns = df.columns.str.strip()

In [21]:
df['marks']

0    56.77
1    59.77
2    76.88
3    69.66
4    63.28
5    49.55
6    65.34
7    68.33
8    56.75
9    78.66
Name: marks, dtype: float64

In [22]:
# duplicate value

In [23]:
df

   roll     name class  marks  age
0     1     Anil    TE  56.77   22
1     2     Amit    TE  59.77   21
2     3   Aniket    BE  76.88   19
3     4  Ajinkya    TE  69.66   20
4     5     Asha    TE  63.28   20
5     6   Ayesha    BE  49.55   20
6     7     Amar    BE  65.34   19
7     8    Amita    BE  68.33   23
8     9     Amol    TE  56.75   20
9    10    Anmol    BE  78.66   21

In [24]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.drop_duplicates(inplace=True)

In [27]:
df

   roll     name class  marks  age
0     1     Anil    TE  56.77   22
1     2     Amit    TE  59.77   21
2     3   Aniket    BE  76.88   19
3     4  Ajinkya    TE  69.66   20
4     5     Asha    TE  63.28   20
5     6   Ayesha    BE  49.55   20
6     7     Amar    BE  65.34   19
7     8    Amita    BE  68.33   23
8     9     Amol    TE  56.75   20
9    10    Anmol    BE  78.66   21

In [28]:
# missing values

In [29]:
df.count()

roll     10
name     10
class    10
marks    10
age      10
dtype: int64

In [30]:
df.isnull().sum()

roll     0
name     0
class    0
marks    0
age      0
dtype: int64

In [31]:
df.isnull().sum().sum()

np.int64(0)

In [32]:
# removing rows with null value

In [33]:
df.dropna()

   roll     name class  marks  age
0     1     Anil    TE  56.77   22
1     2     Amit    TE  59.77   21
2     3   Aniket    BE  76.88   19
3     4  Ajinkya    TE  69.66   20
4     5     Asha    TE  63.28   20
5     6   Ayesha    BE  49.55   20
6     7     Amar    BE  65.34   19
7     8    Amita    BE  68.33   23
8     9     Amol    TE  56.75   20
9    10    Anmol    BE  78.66   21

In [34]:
# filling the missing values

In [35]:
df

   roll     name class  marks  age
0     1     Anil    TE  56.77   22
1     2     Amit    TE  59.77   21
2     3   Aniket    BE  76.88   19
3     4  Ajinkya    TE  69.66   20
4     5     Asha    TE  63.28   20
5     6   Ayesha    BE  49.55   20
6     7     Amar    BE  65.34   19
7     8    Amita    BE  68.33   23
8     9     Amol    TE  56.75   20
9    10    Anmol    BE  78.66   21

In [36]:
df['marks'].fillna(45)
# fill with avg marks

0    56.77
1    59.77
2    76.88
3    69.66
4    63.28
5    49.55
6    65.34
7    68.33
8    56.75
9    78.66
Name: marks, dtype: float64

In [37]:
df['marks'].fillna(df['marks'].mean())

0    56.77
1    59.77
2    76.88
3    69.66
4    63.28
5    49.55
6    65.34
7    68.33
8    56.75
9    78.66
Name: marks, dtype: float64

In [38]:
df['age'].fillna(df['age'].median())

0    22
1    21
2    19
3    20
4    20
5    20
6    19
7    23
8    20
9    21
Name: age, dtype: int64

In [39]:
# fill class column value with mode

In [40]:
df['class'].mode()

0    BE
1    TE
Name: class, dtype: object

In [41]:
df['class'].fillna(df['class'].mode()[0])

0    TE
1    TE
2    BE
3    TE
4    TE
5    BE
6    BE
7    BE
8    TE
9    BE
Name: class, dtype: object

In [42]:
df

   roll     name class  marks  age
0     1     Anil    TE  56.77   22
1     2     Amit    TE  59.77   21
2     3   Aniket    BE  76.88   19
3     4  Ajinkya    TE  69.66   20
4     5     Asha    TE  63.28   20
5     6   Ayesha    BE  49.55   20
6     7     Amar    BE  65.34   19
7     8    Amita    BE  68.33   23
8     9     Amol    TE  56.75   20
9    10    Anmol    BE  78.66   21

In [43]:
df.ffill()

   roll     name class  marks  age
0     1     Anil    TE  56.77   22
1     2     Amit    TE  59.77   21
2     3   Aniket    BE  76.88   19
3     4  Ajinkya    TE  69.66   20
4     5     Asha    TE  63.28   20
5     6   Ayesha    BE  49.55   20
6     7     Amar    BE  65.34   19
7     8    Amita    BE  68.33   23
8     9     Amol    TE  56.75   20
9    10    Anmol    BE  78.66   21

In [44]:
df.bfill(inplace=True)

In [45]:
df.isnull().sum()

roll     0
name     0
class    0
marks    0
age      0
dtype: int64